### ISSUE TITLE
정보수정에서의 오류 발견 보고

### ISSUE THREAD

**Issue by archifeeld13** [songjein/akfd#51]
정보수정에서 URL(마이필드 주소 설정)을 먼저 입력하지 않고 다른 정보를 수정하면 수정이 안되는 오류가 발견됨
case1) 주소설정을 하지 않은 상태에서 프로필 사진을 바꾸면 변경되지 않는데 URL을 입력한 뒤에 프사를 바꾸면 적용됨.
case2)주소설정을 하지 않은 상태에서 스킬을 설정하면 수정되지 않다가 URL을 입력하면 스킬이 등록됨.

이와같이 개인정보를 수정하기위해선 현재 URL을 필수, 우선적으로 바꾸어 주어야 다른것이 수정이 된다는 문제점을 발견하였음.

**Comment by songjein** [comment]
주소설정 안적었을때 처리를 안했었네..
